Repository rpc404/playpoint-user, pull requests merged in 2022-11, with the labels that each got.

#26 Updates on Page
  src/pages/fixture/index.jsx
Labels: documentation, enhancement

#28 Making Team Logo Dynamic
  src/pages/predict/index.jsx
Labels: documentation, enhancement, help wanted

#29 Updated bar with context
  src/App.jsx
  src/components/Navbar/index.jsx
  src/components/PredictionTabs/components/TabByPool.jsx
  src/contexts/WalletRPC/RPCContext.jsx
  src/contexts/WalletRPC/RPCReducer.js
  src/main.jsx
  src/pages/home/index.jsx
  src/pages/predict/index.jsx
  src/pages/profile/index.jsx
  src/utils/RPC.js
  src/utils/Routers.jsx
Labels: enhancement

#30 profile page
  src/pages/profile/index.jsx
  src/pages/profile/styles/style.css
  src/pages/profile/styles/style.css.map
  src/pages/profile/styles/style.scss
Labels: enhancement
